version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql_shop_db
    environment:
      MYSQL_ROOT_PASSWORD: 01052002
      MYSQL_DATABASE: shop
      MYSQL_USER: phuc
      MYSQL_PASSWORD: phuc152002
    ports:
      - "3303:3306"

  app:
    image: phuc1502tranxuan/shopshirt03
    container_name: shopshirt03
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8182:6868"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: shop
      MYSQL_USER: phuc
      MYSQL_PASSWORD: phuc152002

